extends: airbnb-base
plugins:
  - import
rules:
  no-cond-assing: off
  no-param-reassign: 
    - error
    - props: false
  no-console: 
    - error
    - allow: 
      - log
      - warn
      - error
